### ISSUE TITLE
Disable generating code coverage html

### ISSUE THREAD

**Issue by trylika** [ongr-io/OXIDConnectorBundle#3]

**Comment by tautrimas** [comment]
Why should it be disabled? ConnectionsBundle uses it.

**Comment by trylika** [comment]
Generating html in travis makes test process longer, but can't be viewed anywhere. That's why it should be disabled by default. If anybody needs it, they can copy phpunit.xml.dist -> phpunit.xml and uncomment generating html coverage line.

Also, i already fixed this issue, but forgot to close it, sorry, my bad :)

**Comment by tautrimas** [comment]
Code coverage is enabled in Travis using console command parameters. Code coverage is being uploaded and visible in Scrutinizer.

Parameters from `phpunit.xml.dist` is used only for local development and is included for the developer to conveniently comment / uncomment. Please, leave them intact.
